-- 1. Devuelve un listado con el identificador, nombre y los apellidos de todos los clientes que han realizado algún pedido. El listado debe estar ordenado alfabéticamente y se deben eliminar los elementos repetidos.
SELECT DISTINCT cliente.id, cliente.nombre, cliente.apellido1, cliente.apellido2 FROM cliente, pedido WHERE cliente.id = pedido.id_cliente ORDER BY cliente.nombre, cliente.apellido1, cliente.apellido2;
-- 2. Devuelve un listado que muestre todos los pedidos que ha realizado cada cliente. El resultado debe mostrar todos los datos de los pedidos y del cliente. El listado debe mostrar los datos de los clientes ordenados alfabéticamente.
SELECT pedido.id, pedido.total, pedido.fecha, cliente.nombre, cliente.apellido1, cliente.apellido2 FROM pedido, cliente WHERE pedido.id_cliente = cliente.id ORDER BY cliente.nombre, cliente.apellido1, cliente.apellido2;
-- 3. Devuelve un listado que muestre todos los pedidos en los que ha participado un comercial. El resultado debe mostrar todos los datos de los pedidos y de los comerciales. El listado debe mostrar los datos de los comerciales ordenados alfabéticamente.
SELECT pedido.id, pedido.total, pedido.fecha, comercial.nombre, comercial.apellido1, comercial.apellido2 FROM pedido, comercial WHERE pedido.id_comercial = comercial.id ORDER BY comercial.nombre, comercial.apellido1, comercial.apellido2;
-- 4. Devuelve un listado que muestre todos los clientes, con todos los pedidos que han realizado y con los datos de los comerciales asociados a cada pedido.
SELECT cliente.nombre, cliente.apellido1, cliente.apellido2, pedido.id, pedido.total, pedido.fecha, comercial.nombre, comercial.apellido1, comercial.apellido2 FROM cliente, pedido, comercial WHERE cliente.id = pedido.id_cliente AND pedido.id_comercial = comercial.id ORDER BY cliente.nombre, cliente.apellido1, cliente.apellido2;
-- 5. Devuelve un listado de todos los clientes que realizaron un pedido durante el año 2017, cuya cantidad esté entre 300 € y 1000 €.
SELECT cliente.nombre, cliente.apellido1, cliente.apellido2 FROM cliente, pedido WHERE cliente.id = pedido.id_cliente AND pedido.total BETWEEN 300 AND 1000 AND YEAR(pedido.fecha) = 2017;
-- 6. Devuelve el nombre y los apellidos de todos los comerciales que ha participado en algún pedido realizado por María Santana Moreno.
SELECT DISTINCT comercial.nombre, comercial.apellido1, comercial.apellido2 FROM comercial, pedido, cliente WHERE comercial.id = pedido.id_comercial AND pedido.id_cliente = cliente.id AND cliente.nombre = "María" AND cliente.apellido1 = "Santana" AND cliente.apellido2 = "Moreno";
-- 7. Devuelve el nombre de todos los clientes que han realizado algún pedido con el comercial Daniel Sáez Vega.
SELECT DISTINCT cliente.nombre, cliente.apellido1, cliente.apellido2 FROM cliente, pedido, comercial WHERE cliente.id = pedido.id_cliente AND pedido.id_comercial = comercial.id AND comercial.nombre = "Daniel" AND comercial.apellido1 = "Sáez" AND comercial.apellido2 = "Vega";