-- 1. Devuelve un listado con los empleados y los datos de los departamentos donde trabaja cada uno.
SELECT empleado.nombre, empleado.apellido1, empleado.apellido2, departamento.nombre, departamento.presupuesto, departamento.gastos FROM empleado, departamento WHERE empleado.id_departamento = departamento.id;
-- 2. Devuelve un listado con los empleados y los datos de los departamentos donde trabaja cada uno. Ordena el resultado, en primer lugar por el nombre del departamento (en orden alfabético) y en segundo lugar por los apellidos y el nombre de los empleados.
SELECT empleado.nombre, empleado.apellido1, empleado.apellido2, departamento.nombre, departamento.presupuesto, departamento.gastos FROM empleado, departamento WHERE empleado.id_departamento = departamento.id ORDRE BY departamento.nombre, empleado.apellido1, empleado.apellido2, empleado.nombre;
-- 3. Devuelve un listado con el identificador y el nombre del departamento, solamente de aquellos departamentos que tienen empleados.
SELECT departamento.id, departamento.nombre FROM departamento, empleado WHERE departamento.id = empleado.id_departamento GROUP BY departamento.id;
-- 4. Devuelve un listado con el identificador, el nombre del departamento y el valor del presupuesto actual del que dispone, solamente de aquellos departamentos que tienen empleados. El valor del presupuesto actual lo puede calcular restando al valor del presupuesto inicial (columna presupuesto) el valor de los gastos que ha generado (columna gastos).
SELECT departamento.id, departamento.nombre, (departamento.presupuesto - departamento.gastos) AS presupuesto_actual FROM departamento, empleado WHERE departamento.id = empleado.id_departamento GROUP BY departamento.id;
-- 5. Devuelve el nombre del departamento donde trabaja el empleado que tiene el nif 38382980M.
SELECT departamento.nombre FROM empleado, departamento WHERE empleado.id_departamento = departamento.id AND empleado.nif = "38382980M";
-- 6. Devuelve el nombre del departamento donde trabaja el empleado Pepe Ruiz Santana.
SELECT departamento.nombre FROM empleado, departamento WHERE empleado.id_departamento = departamento.id AND empleado.nombre = "Pepe" AND empleado.apellido1 = "Ruiz" AND empleado.apellido2 = "Santana";
-- 7. Devuelve un listado con los datos de los empleados que trabajan en el departamento de I+D. Ordena el resultado alfabéticamente.
SELECT empleado.nombre, empleado.apellido1, empleado.apellido2, departamento.nombre FROM empleado, departamento WHERE empleado.id_departamento = departamento.id AND departamento.nombre = "I+D" ORDER BY empleado.apellido1, empleado.apellido2, empleado.nombre;
-- 8. Devuelve un listado con los datos de los empleados que trabajan en el departamento de Sistemas, Contabilidad o I+D. Ordena el resultado alfabéticamente.
SELECT empleado.nombre, empleado.apellido1, empleado.apellido2, departamento.nombre FROM empleado, departamento WHERE empleado.id_departamento = departamento.id AND (departamento.nombre = "Sistemas" OR departamento.nombre = "Contabilidad" OR departamento.nombre = "I+D") ORDER BY empleado.apellido1, empleado.apellido2, empleado.nombre;
-- 9. Devuelve una lista con el nombre de los empleados que tienen los departamentos que no tienen un presupuesto entre 100000 y 200000 euros.
SELECT empleado.nombre, empleado.apellido1, empleado.apellido2 FROM empleado, departamento WHERE empleado.id_departamento = departamento.id AND (departamento.presupuesto < 100000 OR departamento.presupuesto > 200000);
-- 10. Devuelve un listado con el nombre de los departamentos donde existe algún empleado cuyo segundo apellido sea NULL. Tenga en cuenta que no debe mostrar nombres de departamentos que estén repetidos.
SELECT DISTINCT departamento.nombre FROM empleado, departamento WHERE empleado.id_departamento = departamento.id AND empleado.apellido2 IS NULL;